version: "3.7"

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: greenwood_mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306